version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_blog
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - ./backend/config/db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: blog_backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: blog
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["node", "server.js"]

  frontend:
    build: ./frontend
    container_name: blog_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  mysql_data:
